//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckPublicTransportRelations.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LastOpenStreetMapBusStopRefresh {
            get {
                return ((global::System.DateTime)(this["LastOpenStreetMapBusStopRefresh"]));
            }
            set {
                this["LastOpenStreetMapBusStopRefresh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LastTravelineDownload {
            get {
                return ((global::System.DateTime)(this["LastTravelineDownload"]));
            }
            set {
                this["LastTravelineDownload"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LastServiceExtract {
            get {
                return ((global::System.DateTime)(this["LastServiceExtract"]));
            }
            set {
                this["LastServiceExtract"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LastOpenStreetMapDownload {
            get {
                return ((global::System.DateTime)(this["LastOpenStreetMapDownload"]));
            }
            set {
                this["LastOpenStreetMapDownload"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://overpass-api.de/api/interpreter")]
        public string OverpassServer {
            get {
                return ((string)(this["OverpassServer"]));
            }
            set {
                this["OverpassServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("?data=")]
        public string OverpassQueryPrefix {
            get {
                return ((string)(this["OverpassQueryPrefix"]));
            }
            set {
                this["OverpassQueryPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp.tnds.basemap.co.uk")]
        public string TravelineSite {
            get {
                return ((string)(this["TravelineSite"]));
            }
            set {
                this["TravelineSite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TravelineUsername {
            get {
                return ((string)(this["TravelineUsername"]));
            }
            set {
                this["TravelineUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TravelinePassword {
            get {
                return ((string)(this["TravelinePassword"]));
            }
            set {
                this["TravelinePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LocalPath {
            get {
                return ((string)(this["LocalPath"]));
            }
            set {
                this["LocalPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMatchedServices {
            get {
                return ((bool)(this["ShowMatchedServices"]));
            }
            set {
                this["ShowMatchedServices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMatchedRoutes {
            get {
                return ((bool)(this["ShowMatchedRoutes"]));
            }
            set {
                this["ShowMatchedRoutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMatchedFromToNames {
            get {
                return ((bool)(this["ShowMatchedFromToNames"]));
            }
            set {
                this["ShowMatchedFromToNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedLocation {
            get {
                return ((string)(this["SelectedLocation"]));
            }
            set {
                this["SelectedLocation"] = value;
            }
        }
    }
}
